#!/usr/bin/env node
// build.js — generates config.js from environment variables
// Run: node build.js
// Platforms set env vars in their dashboard; this script reads them at build time.

const fs = require('fs');

const url = process.env.SUPABASE_URL || '';
const key = process.env.SUPABASE_ANON_KEY || '';

if (!url || !key) {
  console.error('ERROR: SUPABASE_URL and SUPABASE_ANON_KEY must be set.');
  console.error('  Cloudflare Pages: Settings → Environment variables');
  console.error('  Netlify:          Site settings → Environment variables');
  console.error('  Vercel:           Project settings → Environment variables');
  process.exit(1);
}

const output = `// Auto-generated by build.js — do not edit manually
window.DRMSA_CONFIG = {
  SUPABASE_URL: "${url}",
  SUPABASE_ANON_KEY: "${key}",
};
`;

fs.writeFileSync('config.js', output);
console.log('✓ config.js written from environment variables');
